version : '3.9'

services:
  password_test:
    image: nginx:1.13.0-alpine
    container_name: password_test_site
    ports:
      - "8080:80"
    volumes:
      - ./password_test:/var/www/html/agnos
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

  docker_proxy:
      image: nginx
      container_name: docker_proxy
      volumes:
        - ./nginx/conf.d:/etc/nginx/conf.d
      ports:
        - "80:80"

  postgres:
    image : postgres:12
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
  pg-admin:
    image : dpage/pgadmin4:6
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@email.com 
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_LISTEN_PORT=5050
    ports:
      - "5050:5050"
volumes:
  data: 
